/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as LocaleRouteImport } from './routes/$locale'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkbenchRouteImport } from './routes/app/workbench'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppDashboardIndexRouteImport } from './routes/app/dashboard/index'
import { Route as AppWorkbenchIdRouteImport } from './routes/app/workbench/$id'
import { Route as AppDashboardTemplatesRouteImport } from './routes/app/dashboard/templates'
import { Route as AppDashboardSettingsRouteImport } from './routes/app/dashboard/settings'
import { Route as AppDashboardResumesRouteImport } from './routes/app/dashboard/resumes'
import { Route as AppDashboardAiRouteImport } from './routes/app/dashboard/ai'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleRoute = LocaleRouteImport.update({
  id: '/$locale',
  path: '/$locale',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkbenchRoute = AppWorkbenchRouteImport.update({
  id: '/workbench',
  path: '/workbench',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardIndexRoute = AppDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppWorkbenchIdRoute = AppWorkbenchIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppWorkbenchRoute,
} as any)
const AppDashboardTemplatesRoute = AppDashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardSettingsRoute = AppDashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardResumesRoute = AppDashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppDashboardRoute,
} as any)
const AppDashboardAiRoute = AppDashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppDashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/workbench': typeof AppWorkbenchRouteWithChildren
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/app': typeof AppRouteWithChildren
  '/app/workbench': typeof AppWorkbenchRouteWithChildren
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard': typeof AppDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale': typeof LocaleRoute
  '/app': typeof AppRouteWithChildren
  '/app/dashboard': typeof AppDashboardRouteWithChildren
  '/app/workbench': typeof AppWorkbenchRouteWithChildren
  '/app/dashboard/ai': typeof AppDashboardAiRoute
  '/app/dashboard/resumes': typeof AppDashboardResumesRoute
  '/app/dashboard/settings': typeof AppDashboardSettingsRoute
  '/app/dashboard/templates': typeof AppDashboardTemplatesRoute
  '/app/workbench/$id': typeof AppWorkbenchIdRoute
  '/app/dashboard/': typeof AppDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$locale'
    | '/app'
    | '/app/dashboard'
    | '/app/workbench'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$locale'
    | '/app'
    | '/app/workbench'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/workbench/$id'
    | '/app/dashboard'
  id:
    | '__root__'
    | '/'
    | '/$locale'
    | '/app'
    | '/app/dashboard'
    | '/app/workbench'
    | '/app/dashboard/ai'
    | '/app/dashboard/resumes'
    | '/app/dashboard/settings'
    | '/app/dashboard/templates'
    | '/app/workbench/$id'
    | '/app/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleRoute: typeof LocaleRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale': {
      id: '/$locale'
      path: '/$locale'
      fullPath: '/$locale'
      preLoaderRoute: typeof LocaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/workbench': {
      id: '/app/workbench'
      path: '/workbench'
      fullPath: '/app/workbench'
      preLoaderRoute: typeof AppWorkbenchRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/dashboard/': {
      id: '/app/dashboard/'
      path: '/'
      fullPath: '/app/dashboard/'
      preLoaderRoute: typeof AppDashboardIndexRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/workbench/$id': {
      id: '/app/workbench/$id'
      path: '/$id'
      fullPath: '/app/workbench/$id'
      preLoaderRoute: typeof AppWorkbenchIdRouteImport
      parentRoute: typeof AppWorkbenchRoute
    }
    '/app/dashboard/templates': {
      id: '/app/dashboard/templates'
      path: '/templates'
      fullPath: '/app/dashboard/templates'
      preLoaderRoute: typeof AppDashboardTemplatesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/settings': {
      id: '/app/dashboard/settings'
      path: '/settings'
      fullPath: '/app/dashboard/settings'
      preLoaderRoute: typeof AppDashboardSettingsRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/resumes': {
      id: '/app/dashboard/resumes'
      path: '/resumes'
      fullPath: '/app/dashboard/resumes'
      preLoaderRoute: typeof AppDashboardResumesRouteImport
      parentRoute: typeof AppDashboardRoute
    }
    '/app/dashboard/ai': {
      id: '/app/dashboard/ai'
      path: '/ai'
      fullPath: '/app/dashboard/ai'
      preLoaderRoute: typeof AppDashboardAiRouteImport
      parentRoute: typeof AppDashboardRoute
    }
  }
}

interface AppDashboardRouteChildren {
  AppDashboardAiRoute: typeof AppDashboardAiRoute
  AppDashboardResumesRoute: typeof AppDashboardResumesRoute
  AppDashboardSettingsRoute: typeof AppDashboardSettingsRoute
  AppDashboardTemplatesRoute: typeof AppDashboardTemplatesRoute
  AppDashboardIndexRoute: typeof AppDashboardIndexRoute
}

const AppDashboardRouteChildren: AppDashboardRouteChildren = {
  AppDashboardAiRoute: AppDashboardAiRoute,
  AppDashboardResumesRoute: AppDashboardResumesRoute,
  AppDashboardSettingsRoute: AppDashboardSettingsRoute,
  AppDashboardTemplatesRoute: AppDashboardTemplatesRoute,
  AppDashboardIndexRoute: AppDashboardIndexRoute,
}

const AppDashboardRouteWithChildren = AppDashboardRoute._addFileChildren(
  AppDashboardRouteChildren,
)

interface AppWorkbenchRouteChildren {
  AppWorkbenchIdRoute: typeof AppWorkbenchIdRoute
}

const AppWorkbenchRouteChildren: AppWorkbenchRouteChildren = {
  AppWorkbenchIdRoute: AppWorkbenchIdRoute,
}

const AppWorkbenchRouteWithChildren = AppWorkbenchRoute._addFileChildren(
  AppWorkbenchRouteChildren,
)

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRouteWithChildren
  AppWorkbenchRoute: typeof AppWorkbenchRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRouteWithChildren,
  AppWorkbenchRoute: AppWorkbenchRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleRoute: LocaleRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
